//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelVoucher
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", ConfigurationName="TravelVoucher.travelvoucher_Port")]
    public interface travelvoucher_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/travelvoucher:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelVoucher.Read_Result> ReadAsync(TravelVoucher.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/travelvoucher:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelVoucher.ReadByRecId_Result> ReadByRecIdAsync(TravelVoucher.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/travelvoucher:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelVoucher.ReadMultiple_Result> ReadMultipleAsync(TravelVoucher.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/travelvoucher:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelVoucher.IsUpdated_Result> IsUpdatedAsync(TravelVoucher.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/travelvoucher:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelVoucher.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(TravelVoucher.GetRecIdFromKey request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/travelvoucher:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelVoucher.Create_Result> CreateAsync(TravelVoucher.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/travelvoucher:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelVoucher.CreateMultiple_Result> CreateMultipleAsync(TravelVoucher.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/travelvoucher:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelVoucher.Update_Result> UpdateAsync(TravelVoucher.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/travelvoucher:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelVoucher.UpdateMultiple_Result> UpdateMultipleAsync(TravelVoucher.UpdateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/travelvoucher:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TravelVoucher.Delete_Result> DeleteAsync(TravelVoucher.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher")]
    public partial class travelvoucher
    {
        
        private string keyField;
        
        private string travel_Order_Form_NoField;
        
        private string travelrs_ID_NoField;
        
        private string travelers_NameField;
        
        private string designationField;
        
        private string departmentField;
        
        private decimal no_of_Days_PlannedField;
        
        private bool no_of_Days_PlannedFieldSpecified;
        
        private System.DateTime actual_Departure_Date_ADField;
        
        private bool actual_Departure_Date_ADFieldSpecified;
        
        private System.DateTime actual_Arrival_Date_ADField;
        
        private bool actual_Arrival_Date_ADFieldSpecified;
        
        private decimal no_of_Days_ActualField;
        
        private bool no_of_Days_ActualFieldSpecified;
        
        private string fulfillment_of_PurposeField;
        
        private bool postedField;
        
        private bool postedFieldSpecified;
        
        private string posted_ByField;
        
        private System.DateTime posted_DateField;
        
        private bool posted_DateFieldSpecified;
        
        private System.DateTime depature_Date_ADField;
        
        private bool depature_Date_ADFieldSpecified;
        
        private System.DateTime arrival_Date_ADField;
        
        private bool arrival_Date_ADFieldSpecified;
        
        private Mode_Of_Transportation mode_Of_TransportationField;
        
        private bool mode_Of_TransportationFieldSpecified;
        
        private string travel_Destination_IField;
        
        private string travel_Destination_IIField;
        
        private string travel_Destination_IIIField;
        
        private decimal lodging_AllowanceField;
        
        private bool lodging_AllowanceFieldSpecified;
        
        private decimal fooding_AllowanceField;
        
        private bool fooding_AllowanceFieldSpecified;
        
        private decimal travel_Allowance_90PercentField;
        
        private bool travel_Allowance_90PercentFieldSpecified;
        
        private decimal daily_Allowance_90PercentField;
        
        private bool daily_Allowance_90PercentFieldSpecified;
        
        private decimal local_TransportationField;
        
        private bool local_TransportationFieldSpecified;
        
        private decimal fuel_Expenses_NrsField;
        
        private bool fuel_Expenses_NrsFieldSpecified;
        
        private decimal guest_Expenses_NrsField;
        
        private bool guest_Expenses_NrsFieldSpecified;
        
        private decimal other_Expenses_NrsField;
        
        private bool other_Expenses_NrsFieldSpecified;
        
        private decimal advance_AmountField;
        
        private bool advance_AmountFieldSpecified;
        
        private decimal claimed_Travel_ExpensesField;
        
        private bool claimed_Travel_ExpensesFieldSpecified;
        
        private decimal claimed_Driver_AllowanceField;
        
        private bool claimed_Driver_AllowanceFieldSpecified;
        
        private decimal claimed_Fuel_ExpensesField;
        
        private bool claimed_Fuel_ExpensesFieldSpecified;
        
        private decimal claimed_Guest_ExpensesField;
        
        private bool claimed_Guest_ExpensesFieldSpecified;
        
        private decimal total_Claimed_AmountField;
        
        private bool total_Claimed_AmountFieldSpecified;
        
        private decimal travel_Allowance_100PercentField;
        
        private bool travel_Allowance_100PercentFieldSpecified;
        
        private decimal daily_Allowance_100PercentField;
        
        private bool daily_Allowance_100PercentFieldSpecified;
        
        private decimal approved_Travel_ExpensesField;
        
        private bool approved_Travel_ExpensesFieldSpecified;
        
        private decimal approved_Driver_AllowanceField;
        
        private bool approved_Driver_AllowanceFieldSpecified;
        
        private decimal approved_Fuel_ExpensesField;
        
        private bool approved_Fuel_ExpensesFieldSpecified;
        
        private decimal approved_Guest_ExpensesField;
        
        private bool approved_Guest_ExpensesFieldSpecified;
        
        private decimal total_Approved_AmountField;
        
        private bool total_Approved_AmountFieldSpecified;
        
        private bool settledField;
        
        private bool settledFieldSpecified;
        
        private string settled_ByField;
        
        private System.DateTime settled_DateField;
        
        private bool settled_DateFieldSpecified;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        private string recommender_CodeField;
        
        private string recommender_NameField;
        
        private string approver_CodeField;
        
        private string approver_NameField;
        
        private string hR_CodeField;
        
        private string hR_NameField;
        
        private string journal_Template_NameField;
        
        private string journal_Batch_NameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Travel_Order_Form_No
        {
            get
            {
                return this.travel_Order_Form_NoField;
            }
            set
            {
                this.travel_Order_Form_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Travelr\'s_ID_No", Order=2)]
        public string Travelrs_ID_No
        {
            get
            {
                return this.travelrs_ID_NoField;
            }
            set
            {
                this.travelrs_ID_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Traveler\'s_Name", Order=3)]
        public string Travelers_Name
        {
            get
            {
                return this.travelers_NameField;
            }
            set
            {
                this.travelers_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Designation
        {
            get
            {
                return this.designationField;
            }
            set
            {
                this.designationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal No_of_Days_Planned
        {
            get
            {
                return this.no_of_Days_PlannedField;
            }
            set
            {
                this.no_of_Days_PlannedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool No_of_Days_PlannedSpecified
        {
            get
            {
                return this.no_of_Days_PlannedFieldSpecified;
            }
            set
            {
                this.no_of_Days_PlannedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=7)]
        public System.DateTime Actual_Departure_Date_AD
        {
            get
            {
                return this.actual_Departure_Date_ADField;
            }
            set
            {
                this.actual_Departure_Date_ADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Actual_Departure_Date_ADSpecified
        {
            get
            {
                return this.actual_Departure_Date_ADFieldSpecified;
            }
            set
            {
                this.actual_Departure_Date_ADFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=8)]
        public System.DateTime Actual_Arrival_Date_AD
        {
            get
            {
                return this.actual_Arrival_Date_ADField;
            }
            set
            {
                this.actual_Arrival_Date_ADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Actual_Arrival_Date_ADSpecified
        {
            get
            {
                return this.actual_Arrival_Date_ADFieldSpecified;
            }
            set
            {
                this.actual_Arrival_Date_ADFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal No_of_Days_Actual
        {
            get
            {
                return this.no_of_Days_ActualField;
            }
            set
            {
                this.no_of_Days_ActualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool No_of_Days_ActualSpecified
        {
            get
            {
                return this.no_of_Days_ActualFieldSpecified;
            }
            set
            {
                this.no_of_Days_ActualFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Fulfillment_of_Purpose
        {
            get
            {
                return this.fulfillment_of_PurposeField;
            }
            set
            {
                this.fulfillment_of_PurposeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool Posted
        {
            get
            {
                return this.postedField;
            }
            set
            {
                this.postedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PostedSpecified
        {
            get
            {
                return this.postedFieldSpecified;
            }
            set
            {
                this.postedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Posted_By
        {
            get
            {
                return this.posted_ByField;
            }
            set
            {
                this.posted_ByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=13)]
        public System.DateTime Posted_Date
        {
            get
            {
                return this.posted_DateField;
            }
            set
            {
                this.posted_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Posted_DateSpecified
        {
            get
            {
                return this.posted_DateFieldSpecified;
            }
            set
            {
                this.posted_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=14)]
        public System.DateTime Depature_Date_AD
        {
            get
            {
                return this.depature_Date_ADField;
            }
            set
            {
                this.depature_Date_ADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Depature_Date_ADSpecified
        {
            get
            {
                return this.depature_Date_ADFieldSpecified;
            }
            set
            {
                this.depature_Date_ADFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=15)]
        public System.DateTime Arrival_Date_AD
        {
            get
            {
                return this.arrival_Date_ADField;
            }
            set
            {
                this.arrival_Date_ADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Arrival_Date_ADSpecified
        {
            get
            {
                return this.arrival_Date_ADFieldSpecified;
            }
            set
            {
                this.arrival_Date_ADFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public Mode_Of_Transportation Mode_Of_Transportation
        {
            get
            {
                return this.mode_Of_TransportationField;
            }
            set
            {
                this.mode_Of_TransportationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Mode_Of_TransportationSpecified
        {
            get
            {
                return this.mode_Of_TransportationFieldSpecified;
            }
            set
            {
                this.mode_Of_TransportationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Travel_Destination_I
        {
            get
            {
                return this.travel_Destination_IField;
            }
            set
            {
                this.travel_Destination_IField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Travel_Destination_II
        {
            get
            {
                return this.travel_Destination_IIField;
            }
            set
            {
                this.travel_Destination_IIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Travel_Destination_III
        {
            get
            {
                return this.travel_Destination_IIIField;
            }
            set
            {
                this.travel_Destination_IIIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public decimal Lodging_Allowance
        {
            get
            {
                return this.lodging_AllowanceField;
            }
            set
            {
                this.lodging_AllowanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Lodging_AllowanceSpecified
        {
            get
            {
                return this.lodging_AllowanceFieldSpecified;
            }
            set
            {
                this.lodging_AllowanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public decimal Fooding_Allowance
        {
            get
            {
                return this.fooding_AllowanceField;
            }
            set
            {
                this.fooding_AllowanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Fooding_AllowanceSpecified
        {
            get
            {
                return this.fooding_AllowanceFieldSpecified;
            }
            set
            {
                this.fooding_AllowanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public decimal Travel_Allowance_90Percent
        {
            get
            {
                return this.travel_Allowance_90PercentField;
            }
            set
            {
                this.travel_Allowance_90PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Travel_Allowance_90PercentSpecified
        {
            get
            {
                return this.travel_Allowance_90PercentFieldSpecified;
            }
            set
            {
                this.travel_Allowance_90PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public decimal Daily_Allowance_90Percent
        {
            get
            {
                return this.daily_Allowance_90PercentField;
            }
            set
            {
                this.daily_Allowance_90PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Daily_Allowance_90PercentSpecified
        {
            get
            {
                return this.daily_Allowance_90PercentFieldSpecified;
            }
            set
            {
                this.daily_Allowance_90PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public decimal Local_Transportation
        {
            get
            {
                return this.local_TransportationField;
            }
            set
            {
                this.local_TransportationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Local_TransportationSpecified
        {
            get
            {
                return this.local_TransportationFieldSpecified;
            }
            set
            {
                this.local_TransportationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public decimal Fuel_Expenses_Nrs
        {
            get
            {
                return this.fuel_Expenses_NrsField;
            }
            set
            {
                this.fuel_Expenses_NrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Fuel_Expenses_NrsSpecified
        {
            get
            {
                return this.fuel_Expenses_NrsFieldSpecified;
            }
            set
            {
                this.fuel_Expenses_NrsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public decimal Guest_Expenses_Nrs
        {
            get
            {
                return this.guest_Expenses_NrsField;
            }
            set
            {
                this.guest_Expenses_NrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Guest_Expenses_NrsSpecified
        {
            get
            {
                return this.guest_Expenses_NrsFieldSpecified;
            }
            set
            {
                this.guest_Expenses_NrsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public decimal Other_Expenses_Nrs
        {
            get
            {
                return this.other_Expenses_NrsField;
            }
            set
            {
                this.other_Expenses_NrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Other_Expenses_NrsSpecified
        {
            get
            {
                return this.other_Expenses_NrsFieldSpecified;
            }
            set
            {
                this.other_Expenses_NrsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public decimal Advance_Amount
        {
            get
            {
                return this.advance_AmountField;
            }
            set
            {
                this.advance_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Advance_AmountSpecified
        {
            get
            {
                return this.advance_AmountFieldSpecified;
            }
            set
            {
                this.advance_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public decimal Claimed_Travel_Expenses
        {
            get
            {
                return this.claimed_Travel_ExpensesField;
            }
            set
            {
                this.claimed_Travel_ExpensesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Claimed_Travel_ExpensesSpecified
        {
            get
            {
                return this.claimed_Travel_ExpensesFieldSpecified;
            }
            set
            {
                this.claimed_Travel_ExpensesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public decimal Claimed_Driver_Allowance
        {
            get
            {
                return this.claimed_Driver_AllowanceField;
            }
            set
            {
                this.claimed_Driver_AllowanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Claimed_Driver_AllowanceSpecified
        {
            get
            {
                return this.claimed_Driver_AllowanceFieldSpecified;
            }
            set
            {
                this.claimed_Driver_AllowanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public decimal Claimed_Fuel_Expenses
        {
            get
            {
                return this.claimed_Fuel_ExpensesField;
            }
            set
            {
                this.claimed_Fuel_ExpensesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Claimed_Fuel_ExpensesSpecified
        {
            get
            {
                return this.claimed_Fuel_ExpensesFieldSpecified;
            }
            set
            {
                this.claimed_Fuel_ExpensesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public decimal Claimed_Guest_Expenses
        {
            get
            {
                return this.claimed_Guest_ExpensesField;
            }
            set
            {
                this.claimed_Guest_ExpensesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Claimed_Guest_ExpensesSpecified
        {
            get
            {
                return this.claimed_Guest_ExpensesFieldSpecified;
            }
            set
            {
                this.claimed_Guest_ExpensesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public decimal Total_Claimed_Amount
        {
            get
            {
                return this.total_Claimed_AmountField;
            }
            set
            {
                this.total_Claimed_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Total_Claimed_AmountSpecified
        {
            get
            {
                return this.total_Claimed_AmountFieldSpecified;
            }
            set
            {
                this.total_Claimed_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public decimal Travel_Allowance_100Percent
        {
            get
            {
                return this.travel_Allowance_100PercentField;
            }
            set
            {
                this.travel_Allowance_100PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Travel_Allowance_100PercentSpecified
        {
            get
            {
                return this.travel_Allowance_100PercentFieldSpecified;
            }
            set
            {
                this.travel_Allowance_100PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public decimal Daily_Allowance_100Percent
        {
            get
            {
                return this.daily_Allowance_100PercentField;
            }
            set
            {
                this.daily_Allowance_100PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Daily_Allowance_100PercentSpecified
        {
            get
            {
                return this.daily_Allowance_100PercentFieldSpecified;
            }
            set
            {
                this.daily_Allowance_100PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public decimal Approved_Travel_Expenses
        {
            get
            {
                return this.approved_Travel_ExpensesField;
            }
            set
            {
                this.approved_Travel_ExpensesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Approved_Travel_ExpensesSpecified
        {
            get
            {
                return this.approved_Travel_ExpensesFieldSpecified;
            }
            set
            {
                this.approved_Travel_ExpensesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public decimal Approved_Driver_Allowance
        {
            get
            {
                return this.approved_Driver_AllowanceField;
            }
            set
            {
                this.approved_Driver_AllowanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Approved_Driver_AllowanceSpecified
        {
            get
            {
                return this.approved_Driver_AllowanceFieldSpecified;
            }
            set
            {
                this.approved_Driver_AllowanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public decimal Approved_Fuel_Expenses
        {
            get
            {
                return this.approved_Fuel_ExpensesField;
            }
            set
            {
                this.approved_Fuel_ExpensesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Approved_Fuel_ExpensesSpecified
        {
            get
            {
                return this.approved_Fuel_ExpensesFieldSpecified;
            }
            set
            {
                this.approved_Fuel_ExpensesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public decimal Approved_Guest_Expenses
        {
            get
            {
                return this.approved_Guest_ExpensesField;
            }
            set
            {
                this.approved_Guest_ExpensesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Approved_Guest_ExpensesSpecified
        {
            get
            {
                return this.approved_Guest_ExpensesFieldSpecified;
            }
            set
            {
                this.approved_Guest_ExpensesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public decimal Total_Approved_Amount
        {
            get
            {
                return this.total_Approved_AmountField;
            }
            set
            {
                this.total_Approved_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Total_Approved_AmountSpecified
        {
            get
            {
                return this.total_Approved_AmountFieldSpecified;
            }
            set
            {
                this.total_Approved_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public bool Settled
        {
            get
            {
                return this.settledField;
            }
            set
            {
                this.settledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SettledSpecified
        {
            get
            {
                return this.settledFieldSpecified;
            }
            set
            {
                this.settledFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string Settled_By
        {
            get
            {
                return this.settled_ByField;
            }
            set
            {
                this.settled_ByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public System.DateTime Settled_Date
        {
            get
            {
                return this.settled_DateField;
            }
            set
            {
                this.settled_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Settled_DateSpecified
        {
            get
            {
                return this.settled_DateFieldSpecified;
            }
            set
            {
                this.settled_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string Recommender_Code
        {
            get
            {
                return this.recommender_CodeField;
            }
            set
            {
                this.recommender_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string Recommender_Name
        {
            get
            {
                return this.recommender_NameField;
            }
            set
            {
                this.recommender_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string Approver_Code
        {
            get
            {
                return this.approver_CodeField;
            }
            set
            {
                this.approver_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string Approver_Name
        {
            get
            {
                return this.approver_NameField;
            }
            set
            {
                this.approver_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string HR_Code
        {
            get
            {
                return this.hR_CodeField;
            }
            set
            {
                this.hR_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string HR_Name
        {
            get
            {
                return this.hR_NameField;
            }
            set
            {
                this.hR_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string Journal_Template_Name
        {
            get
            {
                return this.journal_Template_NameField;
            }
            set
            {
                this.journal_Template_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string Journal_Batch_Name
        {
            get
            {
                return this.journal_Batch_NameField;
            }
            set
            {
                this.journal_Batch_NameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher")]
    public enum Mode_Of_Transportation
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Abroad,
        
        /// <remarks/>
        Local_Vehicle,
        
        /// <remarks/>
        Agni_x0027_s_Vehicle,
        
        /// <remarks/>
        Personal_Vehicle,
        
        /// <remarks/>
        Others,
        
        /// <remarks/>
        By_Air_within_Nepal,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher")]
    public enum Status
    {
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Verified,
        
        /// <remarks/>
        Recommended,
        
        /// <remarks/>
        Approved,
        
        /// <remarks/>
        Rejected,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher")]
    public partial class travelvoucher_Filter
    {
        
        private travelvoucher_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public travelvoucher_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher")]
    public enum travelvoucher_Fields
    {
        
        /// <remarks/>
        Travel_Order_Form_No,
        
        /// <remarks/>
        Travelr_x0027_s_ID_No,
        
        /// <remarks/>
        Traveler_x0027_s_Name,
        
        /// <remarks/>
        Designation,
        
        /// <remarks/>
        Department,
        
        /// <remarks/>
        No_of_Days_Planned,
        
        /// <remarks/>
        Actual_Departure_Date_AD,
        
        /// <remarks/>
        Actual_Arrival_Date_AD,
        
        /// <remarks/>
        No_of_Days_Actual,
        
        /// <remarks/>
        Fulfillment_of_Purpose,
        
        /// <remarks/>
        Posted,
        
        /// <remarks/>
        Posted_By,
        
        /// <remarks/>
        Posted_Date,
        
        /// <remarks/>
        Depature_Date_AD,
        
        /// <remarks/>
        Arrival_Date_AD,
        
        /// <remarks/>
        Mode_Of_Transportation,
        
        /// <remarks/>
        Travel_Destination_I,
        
        /// <remarks/>
        Travel_Destination_II,
        
        /// <remarks/>
        Travel_Destination_III,
        
        /// <remarks/>
        Lodging_Allowance,
        
        /// <remarks/>
        Fooding_Allowance,
        
        /// <remarks/>
        Travel_Allowance_90Percent,
        
        /// <remarks/>
        Daily_Allowance_90Percent,
        
        /// <remarks/>
        Local_Transportation,
        
        /// <remarks/>
        Fuel_Expenses_Nrs,
        
        /// <remarks/>
        Guest_Expenses_Nrs,
        
        /// <remarks/>
        Other_Expenses_Nrs,
        
        /// <remarks/>
        Advance_Amount,
        
        /// <remarks/>
        Claimed_Travel_Expenses,
        
        /// <remarks/>
        Claimed_Driver_Allowance,
        
        /// <remarks/>
        Claimed_Fuel_Expenses,
        
        /// <remarks/>
        Claimed_Guest_Expenses,
        
        /// <remarks/>
        Total_Claimed_Amount,
        
        /// <remarks/>
        Travel_Allowance_100Percent,
        
        /// <remarks/>
        Daily_Allowance_100Percent,
        
        /// <remarks/>
        Approved_Travel_Expenses,
        
        /// <remarks/>
        Approved_Driver_Allowance,
        
        /// <remarks/>
        Approved_Fuel_Expenses,
        
        /// <remarks/>
        Approved_Guest_Expenses,
        
        /// <remarks/>
        Total_Approved_Amount,
        
        /// <remarks/>
        Settled,
        
        /// <remarks/>
        Settled_By,
        
        /// <remarks/>
        Settled_Date,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        Recommender_Code,
        
        /// <remarks/>
        Recommender_Name,
        
        /// <remarks/>
        Approver_Code,
        
        /// <remarks/>
        Approver_Name,
        
        /// <remarks/>
        HR_Code,
        
        /// <remarks/>
        HR_Name,
        
        /// <remarks/>
        Journal_Template_Name,
        
        /// <remarks/>
        Journal_Batch_Name,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        public string Travel_Order_Form_No;
        
        public Read()
        {
        }
        
        public Read(string Travel_Order_Form_No)
        {
            this.Travel_Order_Form_No = Travel_Order_Form_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        public TravelVoucher.travelvoucher travelvoucher;
        
        public Read_Result()
        {
        }
        
        public Read_Result(TravelVoucher.travelvoucher travelvoucher)
        {
            this.travelvoucher = travelvoucher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        public TravelVoucher.travelvoucher travelvoucher;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(TravelVoucher.travelvoucher travelvoucher)
        {
            this.travelvoucher = travelvoucher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public TravelVoucher.travelvoucher_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(TravelVoucher.travelvoucher_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TravelVoucher.travelvoucher[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(TravelVoucher.travelvoucher[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        public TravelVoucher.travelvoucher travelvoucher;
        
        public Create()
        {
        }
        
        public Create(TravelVoucher.travelvoucher travelvoucher)
        {
            this.travelvoucher = travelvoucher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        public TravelVoucher.travelvoucher travelvoucher;
        
        public Create_Result()
        {
        }
        
        public Create_Result(TravelVoucher.travelvoucher travelvoucher)
        {
            this.travelvoucher = travelvoucher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TravelVoucher.travelvoucher[] travelvoucher_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(TravelVoucher.travelvoucher[] travelvoucher_List)
        {
            this.travelvoucher_List = travelvoucher_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TravelVoucher.travelvoucher[] travelvoucher_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(TravelVoucher.travelvoucher[] travelvoucher_List)
        {
            this.travelvoucher_List = travelvoucher_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        public TravelVoucher.travelvoucher travelvoucher;
        
        public Update()
        {
        }
        
        public Update(TravelVoucher.travelvoucher travelvoucher)
        {
            this.travelvoucher = travelvoucher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        public TravelVoucher.travelvoucher travelvoucher;
        
        public Update_Result()
        {
        }
        
        public Update_Result(TravelVoucher.travelvoucher travelvoucher)
        {
            this.travelvoucher = travelvoucher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TravelVoucher.travelvoucher[] travelvoucher_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(TravelVoucher.travelvoucher[] travelvoucher_List)
        {
            this.travelvoucher_List = travelvoucher_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TravelVoucher.travelvoucher[] travelvoucher_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(TravelVoucher.travelvoucher[] travelvoucher_List)
        {
            this.travelvoucher_List = travelvoucher_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class Delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        public string Key;
        
        public Delete()
        {
        }
        
        public Delete(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/travelvoucher", IsWrapped=true)]
    public partial class Delete_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/travelvoucher", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result()
        {
        }
        
        public Delete_Result(bool Delete_Result1)
        {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public interface travelvoucher_PortChannel : TravelVoucher.travelvoucher_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public partial class travelvoucher_PortClient : System.ServiceModel.ClientBase<TravelVoucher.travelvoucher_Port>, TravelVoucher.travelvoucher_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public travelvoucher_PortClient() : 
                base(travelvoucher_PortClient.GetDefaultBinding(), travelvoucher_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.travelvoucher_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public travelvoucher_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(travelvoucher_PortClient.GetBindingForEndpoint(endpointConfiguration), travelvoucher_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public travelvoucher_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(travelvoucher_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public travelvoucher_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(travelvoucher_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public travelvoucher_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelVoucher.Read_Result> TravelVoucher.travelvoucher_Port.ReadAsync(TravelVoucher.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelVoucher.Read_Result> ReadAsync(string Travel_Order_Form_No)
        {
            TravelVoucher.Read inValue = new TravelVoucher.Read();
            inValue.Travel_Order_Form_No = Travel_Order_Form_No;
            return ((TravelVoucher.travelvoucher_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelVoucher.ReadByRecId_Result> TravelVoucher.travelvoucher_Port.ReadByRecIdAsync(TravelVoucher.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelVoucher.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            TravelVoucher.ReadByRecId inValue = new TravelVoucher.ReadByRecId();
            inValue.recId = recId;
            return ((TravelVoucher.travelvoucher_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelVoucher.ReadMultiple_Result> TravelVoucher.travelvoucher_Port.ReadMultipleAsync(TravelVoucher.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelVoucher.ReadMultiple_Result> ReadMultipleAsync(TravelVoucher.travelvoucher_Filter[] filter, string bookmarkKey, int setSize)
        {
            TravelVoucher.ReadMultiple inValue = new TravelVoucher.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((TravelVoucher.travelvoucher_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelVoucher.IsUpdated_Result> TravelVoucher.travelvoucher_Port.IsUpdatedAsync(TravelVoucher.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelVoucher.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            TravelVoucher.IsUpdated inValue = new TravelVoucher.IsUpdated();
            inValue.Key = Key;
            return ((TravelVoucher.travelvoucher_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelVoucher.GetRecIdFromKey_Result> TravelVoucher.travelvoucher_Port.GetRecIdFromKeyAsync(TravelVoucher.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelVoucher.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            TravelVoucher.GetRecIdFromKey inValue = new TravelVoucher.GetRecIdFromKey();
            inValue.Key = Key;
            return ((TravelVoucher.travelvoucher_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<TravelVoucher.Create_Result> CreateAsync(TravelVoucher.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelVoucher.CreateMultiple_Result> CreateMultipleAsync(TravelVoucher.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelVoucher.Update_Result> UpdateAsync(TravelVoucher.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelVoucher.UpdateMultiple_Result> UpdateMultipleAsync(TravelVoucher.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelVoucher.Delete_Result> TravelVoucher.travelvoucher_Port.DeleteAsync(TravelVoucher.Delete request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelVoucher.Delete_Result> DeleteAsync(string Key)
        {
            TravelVoucher.Delete inValue = new TravelVoucher.Delete();
            inValue.Key = Key;
            return ((TravelVoucher.travelvoucher_Port)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.travelvoucher_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.travelvoucher_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://110.34.3.177:4047/MOBAPP/WS/Test Company/Page/travelvoucher");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return travelvoucher_PortClient.GetBindingForEndpoint(EndpointConfiguration.travelvoucher_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return travelvoucher_PortClient.GetEndpointAddress(EndpointConfiguration.travelvoucher_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            travelvoucher_Port,
        }
    }
}
