//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostedLeaveRequestCard
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", ConfigurationName="PostedLeaveRequestCard.postedleaverequestcard_Port")]
    public interface postedleaverequestcard_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedleaverequestcard:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostedLeaveRequestCard.Read_Result> ReadAsync(PostedLeaveRequestCard.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedleaverequestcard:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostedLeaveRequestCard.ReadByRecId_Result> ReadByRecIdAsync(PostedLeaveRequestCard.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedleaverequestcard:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostedLeaveRequestCard.ReadMultiple_Result> ReadMultipleAsync(PostedLeaveRequestCard.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedleaverequestcard:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostedLeaveRequestCard.IsUpdated_Result> IsUpdatedAsync(PostedLeaveRequestCard.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedleaverequestcard:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostedLeaveRequestCard.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(PostedLeaveRequestCard.GetRecIdFromKey request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedleaverequestcard:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostedLeaveRequestCard.Create_Result> CreateAsync(PostedLeaveRequestCard.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedleaverequestcard:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostedLeaveRequestCard.CreateMultiple_Result> CreateMultipleAsync(PostedLeaveRequestCard.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedleaverequestcard:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostedLeaveRequestCard.Update_Result> UpdateAsync(PostedLeaveRequestCard.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedleaverequestcard:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostedLeaveRequestCard.UpdateMultiple_Result> UpdateMultipleAsync(PostedLeaveRequestCard.UpdateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedleaverequestcard:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostedLeaveRequestCard.Delete_Result> DeleteAsync(PostedLeaveRequestCard.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard")]
    public partial class postedleaverequestcard
    {
        
        private string keyField;
        
        private string leave_Request_NoField;
        
        private string employee_NoField;
        
        private string full_NameField;
        
        private System.DateTime requested_DateField;
        
        private bool requested_DateFieldSpecified;
        
        private string work_Shift_CodeField;
        
        private string work_Shift_DescriptionField;
        
        private string leave_Type_CodeField;
        
        private string leave_DescriptionField;
        
        private System.DateTime leave_Start_DateField;
        
        private bool leave_Start_DateFieldSpecified;
        
        private System.DateTime leave_End_DateField;
        
        private bool leave_End_DateFieldSpecified;
        
        private System.DateTime leave_Start_TimeField;
        
        private bool leave_Start_TimeFieldSpecified;
        
        private System.DateTime leave_End_TimeField;
        
        private bool leave_End_TimeFieldSpecified;
        
        private string fiscal_YearField;
        
        private string remarksField;
        
        private Pay_Type pay_TypeField;
        
        private bool pay_TypeFieldSpecified;
        
        private decimal no_of_DaysField;
        
        private bool no_of_DaysFieldSpecified;
        
        private string substitute_Employee_NoField;
        
        private string substitute_Employee_NameField;
        
        private string rejection_RemarksField;
        
        private Leave_Status leave_StatusField;
        
        private bool leave_StatusFieldSpecified;
        
        private string recommender_CodeField;
        
        private string recommender_NameField;
        
        private string approver_CodeField;
        
        private string approver_NameField;
        
        private string hR_CodeField;
        
        private string hR_NameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Leave_Request_No
        {
            get
            {
                return this.leave_Request_NoField;
            }
            set
            {
                this.leave_Request_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Employee_No
        {
            get
            {
                return this.employee_NoField;
            }
            set
            {
                this.employee_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Full_Name
        {
            get
            {
                return this.full_NameField;
            }
            set
            {
                this.full_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime Requested_Date
        {
            get
            {
                return this.requested_DateField;
            }
            set
            {
                this.requested_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Requested_DateSpecified
        {
            get
            {
                return this.requested_DateFieldSpecified;
            }
            set
            {
                this.requested_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Work_Shift_Code
        {
            get
            {
                return this.work_Shift_CodeField;
            }
            set
            {
                this.work_Shift_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Work_Shift_Description
        {
            get
            {
                return this.work_Shift_DescriptionField;
            }
            set
            {
                this.work_Shift_DescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Leave_Type_Code
        {
            get
            {
                return this.leave_Type_CodeField;
            }
            set
            {
                this.leave_Type_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Leave_Description
        {
            get
            {
                return this.leave_DescriptionField;
            }
            set
            {
                this.leave_DescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=9)]
        public System.DateTime Leave_Start_Date
        {
            get
            {
                return this.leave_Start_DateField;
            }
            set
            {
                this.leave_Start_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Leave_Start_DateSpecified
        {
            get
            {
                return this.leave_Start_DateFieldSpecified;
            }
            set
            {
                this.leave_Start_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=10)]
        public System.DateTime Leave_End_Date
        {
            get
            {
                return this.leave_End_DateField;
            }
            set
            {
                this.leave_End_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Leave_End_DateSpecified
        {
            get
            {
                return this.leave_End_DateFieldSpecified;
            }
            set
            {
                this.leave_End_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", Order=11)]
        public System.DateTime Leave_Start_Time
        {
            get
            {
                return this.leave_Start_TimeField;
            }
            set
            {
                this.leave_Start_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Leave_Start_TimeSpecified
        {
            get
            {
                return this.leave_Start_TimeFieldSpecified;
            }
            set
            {
                this.leave_Start_TimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", Order=12)]
        public System.DateTime Leave_End_Time
        {
            get
            {
                return this.leave_End_TimeField;
            }
            set
            {
                this.leave_End_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Leave_End_TimeSpecified
        {
            get
            {
                return this.leave_End_TimeFieldSpecified;
            }
            set
            {
                this.leave_End_TimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Fiscal_Year
        {
            get
            {
                return this.fiscal_YearField;
            }
            set
            {
                this.fiscal_YearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public Pay_Type Pay_Type
        {
            get
            {
                return this.pay_TypeField;
            }
            set
            {
                this.pay_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pay_TypeSpecified
        {
            get
            {
                return this.pay_TypeFieldSpecified;
            }
            set
            {
                this.pay_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public decimal No_of_Days
        {
            get
            {
                return this.no_of_DaysField;
            }
            set
            {
                this.no_of_DaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool No_of_DaysSpecified
        {
            get
            {
                return this.no_of_DaysFieldSpecified;
            }
            set
            {
                this.no_of_DaysFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Substitute_Employee_No
        {
            get
            {
                return this.substitute_Employee_NoField;
            }
            set
            {
                this.substitute_Employee_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Substitute_Employee_Name
        {
            get
            {
                return this.substitute_Employee_NameField;
            }
            set
            {
                this.substitute_Employee_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Rejection_Remarks
        {
            get
            {
                return this.rejection_RemarksField;
            }
            set
            {
                this.rejection_RemarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public Leave_Status Leave_Status
        {
            get
            {
                return this.leave_StatusField;
            }
            set
            {
                this.leave_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Leave_StatusSpecified
        {
            get
            {
                return this.leave_StatusFieldSpecified;
            }
            set
            {
                this.leave_StatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Recommender_Code
        {
            get
            {
                return this.recommender_CodeField;
            }
            set
            {
                this.recommender_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Recommender_Name
        {
            get
            {
                return this.recommender_NameField;
            }
            set
            {
                this.recommender_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Approver_Code
        {
            get
            {
                return this.approver_CodeField;
            }
            set
            {
                this.approver_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Approver_Name
        {
            get
            {
                return this.approver_NameField;
            }
            set
            {
                this.approver_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string HR_Code
        {
            get
            {
                return this.hR_CodeField;
            }
            set
            {
                this.hR_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string HR_Name
        {
            get
            {
                return this.hR_NameField;
            }
            set
            {
                this.hR_NameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard")]
    public enum Pay_Type
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Half_Paid,
        
        /// <remarks/>
        Paid,
        
        /// <remarks/>
        Unpaid,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard")]
    public enum Leave_Status
    {
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Verified,
        
        /// <remarks/>
        Recommended,
        
        /// <remarks/>
        Approved,
        
        /// <remarks/>
        Rejected,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard")]
    public partial class postedleaverequestcard_Filter
    {
        
        private postedleaverequestcard_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public postedleaverequestcard_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard")]
    public enum postedleaverequestcard_Fields
    {
        
        /// <remarks/>
        Leave_Request_No,
        
        /// <remarks/>
        Employee_No,
        
        /// <remarks/>
        Full_Name,
        
        /// <remarks/>
        Requested_Date,
        
        /// <remarks/>
        Work_Shift_Code,
        
        /// <remarks/>
        Work_Shift_Description,
        
        /// <remarks/>
        Leave_Type_Code,
        
        /// <remarks/>
        Leave_Description,
        
        /// <remarks/>
        Leave_Start_Date,
        
        /// <remarks/>
        Leave_End_Date,
        
        /// <remarks/>
        Leave_Start_Time,
        
        /// <remarks/>
        Leave_End_Time,
        
        /// <remarks/>
        Fiscal_Year,
        
        /// <remarks/>
        Remarks,
        
        /// <remarks/>
        Pay_Type,
        
        /// <remarks/>
        No_of_Days,
        
        /// <remarks/>
        Substitute_Employee_No,
        
        /// <remarks/>
        Substitute_Employee_Name,
        
        /// <remarks/>
        Rejection_Remarks,
        
        /// <remarks/>
        Leave_Status,
        
        /// <remarks/>
        Recommender_Code,
        
        /// <remarks/>
        Recommender_Name,
        
        /// <remarks/>
        Approver_Code,
        
        /// <remarks/>
        Approver_Name,
        
        /// <remarks/>
        HR_Code,
        
        /// <remarks/>
        HR_Name,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        public string Recommender_Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=1)]
        public string Employee_No;
        
        public Read()
        {
        }
        
        public Read(string Recommender_Code, string Employee_No)
        {
            this.Recommender_Code = Recommender_Code;
            this.Employee_No = Employee_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        public PostedLeaveRequestCard.postedleaverequestcard postedleaverequestcard;
        
        public Read_Result()
        {
        }
        
        public Read_Result(PostedLeaveRequestCard.postedleaverequestcard postedleaverequestcard)
        {
            this.postedleaverequestcard = postedleaverequestcard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        public PostedLeaveRequestCard.postedleaverequestcard postedleaverequestcard;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(PostedLeaveRequestCard.postedleaverequestcard postedleaverequestcard)
        {
            this.postedleaverequestcard = postedleaverequestcard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public PostedLeaveRequestCard.postedleaverequestcard_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(PostedLeaveRequestCard.postedleaverequestcard_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PostedLeaveRequestCard.postedleaverequestcard[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(PostedLeaveRequestCard.postedleaverequestcard[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        public PostedLeaveRequestCard.postedleaverequestcard postedleaverequestcard;
        
        public Create()
        {
        }
        
        public Create(PostedLeaveRequestCard.postedleaverequestcard postedleaverequestcard)
        {
            this.postedleaverequestcard = postedleaverequestcard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        public PostedLeaveRequestCard.postedleaverequestcard postedleaverequestcard;
        
        public Create_Result()
        {
        }
        
        public Create_Result(PostedLeaveRequestCard.postedleaverequestcard postedleaverequestcard)
        {
            this.postedleaverequestcard = postedleaverequestcard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PostedLeaveRequestCard.postedleaverequestcard[] postedleaverequestcard_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(PostedLeaveRequestCard.postedleaverequestcard[] postedleaverequestcard_List)
        {
            this.postedleaverequestcard_List = postedleaverequestcard_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PostedLeaveRequestCard.postedleaverequestcard[] postedleaverequestcard_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(PostedLeaveRequestCard.postedleaverequestcard[] postedleaverequestcard_List)
        {
            this.postedleaverequestcard_List = postedleaverequestcard_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        public PostedLeaveRequestCard.postedleaverequestcard postedleaverequestcard;
        
        public Update()
        {
        }
        
        public Update(PostedLeaveRequestCard.postedleaverequestcard postedleaverequestcard)
        {
            this.postedleaverequestcard = postedleaverequestcard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        public PostedLeaveRequestCard.postedleaverequestcard postedleaverequestcard;
        
        public Update_Result()
        {
        }
        
        public Update_Result(PostedLeaveRequestCard.postedleaverequestcard postedleaverequestcard)
        {
            this.postedleaverequestcard = postedleaverequestcard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PostedLeaveRequestCard.postedleaverequestcard[] postedleaverequestcard_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(PostedLeaveRequestCard.postedleaverequestcard[] postedleaverequestcard_List)
        {
            this.postedleaverequestcard_List = postedleaverequestcard_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PostedLeaveRequestCard.postedleaverequestcard[] postedleaverequestcard_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(PostedLeaveRequestCard.postedleaverequestcard[] postedleaverequestcard_List)
        {
            this.postedleaverequestcard_List = postedleaverequestcard_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class Delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        public string Key;
        
        public Delete()
        {
        }
        
        public Delete(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", IsWrapped=true)]
    public partial class Delete_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/postedleaverequestcard", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result()
        {
        }
        
        public Delete_Result(bool Delete_Result1)
        {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public interface postedleaverequestcard_PortChannel : PostedLeaveRequestCard.postedleaverequestcard_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public partial class postedleaverequestcard_PortClient : System.ServiceModel.ClientBase<PostedLeaveRequestCard.postedleaverequestcard_Port>, PostedLeaveRequestCard.postedleaverequestcard_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public postedleaverequestcard_PortClient() : 
                base(postedleaverequestcard_PortClient.GetDefaultBinding(), postedleaverequestcard_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.postedleaverequestcard_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public postedleaverequestcard_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(postedleaverequestcard_PortClient.GetBindingForEndpoint(endpointConfiguration), postedleaverequestcard_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public postedleaverequestcard_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(postedleaverequestcard_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public postedleaverequestcard_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(postedleaverequestcard_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public postedleaverequestcard_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PostedLeaveRequestCard.Read_Result> PostedLeaveRequestCard.postedleaverequestcard_Port.ReadAsync(PostedLeaveRequestCard.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<PostedLeaveRequestCard.Read_Result> ReadAsync(string Recommender_Code, string Employee_No)
        {
            PostedLeaveRequestCard.Read inValue = new PostedLeaveRequestCard.Read();
            inValue.Recommender_Code = Recommender_Code;
            inValue.Employee_No = Employee_No;
            return ((PostedLeaveRequestCard.postedleaverequestcard_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PostedLeaveRequestCard.ReadByRecId_Result> PostedLeaveRequestCard.postedleaverequestcard_Port.ReadByRecIdAsync(PostedLeaveRequestCard.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<PostedLeaveRequestCard.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            PostedLeaveRequestCard.ReadByRecId inValue = new PostedLeaveRequestCard.ReadByRecId();
            inValue.recId = recId;
            return ((PostedLeaveRequestCard.postedleaverequestcard_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PostedLeaveRequestCard.ReadMultiple_Result> PostedLeaveRequestCard.postedleaverequestcard_Port.ReadMultipleAsync(PostedLeaveRequestCard.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<PostedLeaveRequestCard.ReadMultiple_Result> ReadMultipleAsync(PostedLeaveRequestCard.postedleaverequestcard_Filter[] filter, string bookmarkKey, int setSize)
        {
            PostedLeaveRequestCard.ReadMultiple inValue = new PostedLeaveRequestCard.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((PostedLeaveRequestCard.postedleaverequestcard_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PostedLeaveRequestCard.IsUpdated_Result> PostedLeaveRequestCard.postedleaverequestcard_Port.IsUpdatedAsync(PostedLeaveRequestCard.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<PostedLeaveRequestCard.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            PostedLeaveRequestCard.IsUpdated inValue = new PostedLeaveRequestCard.IsUpdated();
            inValue.Key = Key;
            return ((PostedLeaveRequestCard.postedleaverequestcard_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PostedLeaveRequestCard.GetRecIdFromKey_Result> PostedLeaveRequestCard.postedleaverequestcard_Port.GetRecIdFromKeyAsync(PostedLeaveRequestCard.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<PostedLeaveRequestCard.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            PostedLeaveRequestCard.GetRecIdFromKey inValue = new PostedLeaveRequestCard.GetRecIdFromKey();
            inValue.Key = Key;
            return ((PostedLeaveRequestCard.postedleaverequestcard_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<PostedLeaveRequestCard.Create_Result> CreateAsync(PostedLeaveRequestCard.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<PostedLeaveRequestCard.CreateMultiple_Result> CreateMultipleAsync(PostedLeaveRequestCard.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<PostedLeaveRequestCard.Update_Result> UpdateAsync(PostedLeaveRequestCard.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<PostedLeaveRequestCard.UpdateMultiple_Result> UpdateMultipleAsync(PostedLeaveRequestCard.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PostedLeaveRequestCard.Delete_Result> PostedLeaveRequestCard.postedleaverequestcard_Port.DeleteAsync(PostedLeaveRequestCard.Delete request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<PostedLeaveRequestCard.Delete_Result> DeleteAsync(string Key)
        {
            PostedLeaveRequestCard.Delete inValue = new PostedLeaveRequestCard.Delete();
            inValue.Key = Key;
            return ((PostedLeaveRequestCard.postedleaverequestcard_Port)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.postedleaverequestcard_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.postedleaverequestcard_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://110.34.3.177:4047/MOBAPP/WS/Test Company/Page/postedleaverequestcard");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return postedleaverequestcard_PortClient.GetBindingForEndpoint(EndpointConfiguration.postedleaverequestcard_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return postedleaverequestcard_PortClient.GetEndpointAddress(EndpointConfiguration.postedleaverequestcard_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            postedleaverequestcard_Port,
        }
    }
}
