//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecommendedTravelVoucher
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", ConfigurationName="RecommendedTravelVoucher.recommendedtravelvoucher_Port")]
    public interface recommendedtravelvoucher_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecommendedTravelVoucher.Read_Result> ReadAsync(RecommendedTravelVoucher.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecommendedTravelVoucher.ReadByRecId_Result> ReadByRecIdAsync(RecommendedTravelVoucher.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecommendedTravelVoucher.ReadMultiple_Result> ReadMultipleAsync(RecommendedTravelVoucher.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecommendedTravelVoucher.IsUpdated_Result> IsUpdatedAsync(RecommendedTravelVoucher.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecommendedTravelVoucher.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(RecommendedTravelVoucher.GetRecIdFromKey request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher")]
    public partial class recommendedtravelvoucher
    {
        
        private string keyField;
        
        private string travel_Order_Form_NoField;
        
        private string travelrs_ID_NoField;
        
        private string travelers_NameField;
        
        private string designationField;
        
        private string departmentField;
        
        private System.DateTime depature_Date_ADField;
        
        private bool depature_Date_ADFieldSpecified;
        
        private System.DateTime arrival_Date_ADField;
        
        private bool arrival_Date_ADFieldSpecified;
        
        private System.DateTime approved_DateField;
        
        private bool approved_DateFieldSpecified;
        
        private System.DateTime recommended_DateField;
        
        private bool recommended_DateFieldSpecified;
        
        private System.DateTime verfied_DateField;
        
        private bool verfied_DateFieldSpecified;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        private bool settledField;
        
        private bool settledFieldSpecified;
        
        private System.DateTime settled_DateField;
        
        private bool settled_DateFieldSpecified;
        
        private string settled_ByField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Travel_Order_Form_No
        {
            get
            {
                return this.travel_Order_Form_NoField;
            }
            set
            {
                this.travel_Order_Form_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Travelr\'s_ID_No", Order=2)]
        public string Travelrs_ID_No
        {
            get
            {
                return this.travelrs_ID_NoField;
            }
            set
            {
                this.travelrs_ID_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Traveler\'s_Name", Order=3)]
        public string Travelers_Name
        {
            get
            {
                return this.travelers_NameField;
            }
            set
            {
                this.travelers_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Designation
        {
            get
            {
                return this.designationField;
            }
            set
            {
                this.designationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime Depature_Date_AD
        {
            get
            {
                return this.depature_Date_ADField;
            }
            set
            {
                this.depature_Date_ADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Depature_Date_ADSpecified
        {
            get
            {
                return this.depature_Date_ADFieldSpecified;
            }
            set
            {
                this.depature_Date_ADFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=7)]
        public System.DateTime Arrival_Date_AD
        {
            get
            {
                return this.arrival_Date_ADField;
            }
            set
            {
                this.arrival_Date_ADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Arrival_Date_ADSpecified
        {
            get
            {
                return this.arrival_Date_ADFieldSpecified;
            }
            set
            {
                this.arrival_Date_ADFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime Approved_Date
        {
            get
            {
                return this.approved_DateField;
            }
            set
            {
                this.approved_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Approved_DateSpecified
        {
            get
            {
                return this.approved_DateFieldSpecified;
            }
            set
            {
                this.approved_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime Recommended_Date
        {
            get
            {
                return this.recommended_DateField;
            }
            set
            {
                this.recommended_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Recommended_DateSpecified
        {
            get
            {
                return this.recommended_DateFieldSpecified;
            }
            set
            {
                this.recommended_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.DateTime Verfied_Date
        {
            get
            {
                return this.verfied_DateField;
            }
            set
            {
                this.verfied_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Verfied_DateSpecified
        {
            get
            {
                return this.verfied_DateFieldSpecified;
            }
            set
            {
                this.verfied_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool Settled
        {
            get
            {
                return this.settledField;
            }
            set
            {
                this.settledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SettledSpecified
        {
            get
            {
                return this.settledFieldSpecified;
            }
            set
            {
                this.settledFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime Settled_Date
        {
            get
            {
                return this.settled_DateField;
            }
            set
            {
                this.settled_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Settled_DateSpecified
        {
            get
            {
                return this.settled_DateFieldSpecified;
            }
            set
            {
                this.settled_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Settled_By
        {
            get
            {
                return this.settled_ByField;
            }
            set
            {
                this.settled_ByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher")]
    public enum Status
    {
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Verified,
        
        /// <remarks/>
        Recommended,
        
        /// <remarks/>
        Approved,
        
        /// <remarks/>
        Rejected,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher")]
    public partial class recommendedtravelvoucher_Filter
    {
        
        private recommendedtravelvoucher_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public recommendedtravelvoucher_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher")]
    public enum recommendedtravelvoucher_Fields
    {
        
        /// <remarks/>
        Travel_Order_Form_No,
        
        /// <remarks/>
        Travelr_x0027_s_ID_No,
        
        /// <remarks/>
        Traveler_x0027_s_Name,
        
        /// <remarks/>
        Designation,
        
        /// <remarks/>
        Department,
        
        /// <remarks/>
        Depature_Date_AD,
        
        /// <remarks/>
        Arrival_Date_AD,
        
        /// <remarks/>
        Approved_Date,
        
        /// <remarks/>
        Recommended_Date,
        
        /// <remarks/>
        Verfied_Date,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        Settled,
        
        /// <remarks/>
        Settled_Date,
        
        /// <remarks/>
        Settled_By,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", Order=0)]
        public string Travel_Order_Form_No;
        
        public Read()
        {
        }
        
        public Read(string Travel_Order_Form_No)
        {
            this.Travel_Order_Form_No = Travel_Order_Form_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", Order=0)]
        public RecommendedTravelVoucher.recommendedtravelvoucher recommendedtravelvoucher;
        
        public Read_Result()
        {
        }
        
        public Read_Result(RecommendedTravelVoucher.recommendedtravelvoucher recommendedtravelvoucher)
        {
            this.recommendedtravelvoucher = recommendedtravelvoucher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", Order=0)]
        public RecommendedTravelVoucher.recommendedtravelvoucher recommendedtravelvoucher;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(RecommendedTravelVoucher.recommendedtravelvoucher recommendedtravelvoucher)
        {
            this.recommendedtravelvoucher = recommendedtravelvoucher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public RecommendedTravelVoucher.recommendedtravelvoucher_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(RecommendedTravelVoucher.recommendedtravelvoucher_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RecommendedTravelVoucher.recommendedtravelvoucher[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(RecommendedTravelVoucher.recommendedtravelvoucher[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/recommendedtravelvoucher", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public interface recommendedtravelvoucher_PortChannel : RecommendedTravelVoucher.recommendedtravelvoucher_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public partial class recommendedtravelvoucher_PortClient : System.ServiceModel.ClientBase<RecommendedTravelVoucher.recommendedtravelvoucher_Port>, RecommendedTravelVoucher.recommendedtravelvoucher_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public recommendedtravelvoucher_PortClient() : 
                base(recommendedtravelvoucher_PortClient.GetDefaultBinding(), recommendedtravelvoucher_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.recommendedtravelvoucher_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public recommendedtravelvoucher_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(recommendedtravelvoucher_PortClient.GetBindingForEndpoint(endpointConfiguration), recommendedtravelvoucher_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public recommendedtravelvoucher_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(recommendedtravelvoucher_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public recommendedtravelvoucher_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(recommendedtravelvoucher_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public recommendedtravelvoucher_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecommendedTravelVoucher.Read_Result> RecommendedTravelVoucher.recommendedtravelvoucher_Port.ReadAsync(RecommendedTravelVoucher.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecommendedTravelVoucher.Read_Result> ReadAsync(string Travel_Order_Form_No)
        {
            RecommendedTravelVoucher.Read inValue = new RecommendedTravelVoucher.Read();
            inValue.Travel_Order_Form_No = Travel_Order_Form_No;
            return ((RecommendedTravelVoucher.recommendedtravelvoucher_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecommendedTravelVoucher.ReadByRecId_Result> RecommendedTravelVoucher.recommendedtravelvoucher_Port.ReadByRecIdAsync(RecommendedTravelVoucher.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecommendedTravelVoucher.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            RecommendedTravelVoucher.ReadByRecId inValue = new RecommendedTravelVoucher.ReadByRecId();
            inValue.recId = recId;
            return ((RecommendedTravelVoucher.recommendedtravelvoucher_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecommendedTravelVoucher.ReadMultiple_Result> RecommendedTravelVoucher.recommendedtravelvoucher_Port.ReadMultipleAsync(RecommendedTravelVoucher.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecommendedTravelVoucher.ReadMultiple_Result> ReadMultipleAsync(RecommendedTravelVoucher.recommendedtravelvoucher_Filter[] filter, string bookmarkKey, int setSize)
        {
            RecommendedTravelVoucher.ReadMultiple inValue = new RecommendedTravelVoucher.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((RecommendedTravelVoucher.recommendedtravelvoucher_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecommendedTravelVoucher.IsUpdated_Result> RecommendedTravelVoucher.recommendedtravelvoucher_Port.IsUpdatedAsync(RecommendedTravelVoucher.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecommendedTravelVoucher.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            RecommendedTravelVoucher.IsUpdated inValue = new RecommendedTravelVoucher.IsUpdated();
            inValue.Key = Key;
            return ((RecommendedTravelVoucher.recommendedtravelvoucher_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecommendedTravelVoucher.GetRecIdFromKey_Result> RecommendedTravelVoucher.recommendedtravelvoucher_Port.GetRecIdFromKeyAsync(RecommendedTravelVoucher.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecommendedTravelVoucher.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            RecommendedTravelVoucher.GetRecIdFromKey inValue = new RecommendedTravelVoucher.GetRecIdFromKey();
            inValue.Key = Key;
            return ((RecommendedTravelVoucher.recommendedtravelvoucher_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.recommendedtravelvoucher_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.recommendedtravelvoucher_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://110.34.3.177:4047/MOBAPP/WS/Test Company/Page/recommendedtravelvoucher");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return recommendedtravelvoucher_PortClient.GetBindingForEndpoint(EndpointConfiguration.recommendedtravelvoucher_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return recommendedtravelvoucher_PortClient.GetEndpointAddress(EndpointConfiguration.recommendedtravelvoucher_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            recommendedtravelvoucher_Port,
        }
    }
}
